# Generated by Django 5.0.1 on 2024-01-31 21:10

from django.db import migrations


def create_initial_data(apps, schema_editor):
    from app.utils import create_contacts, create_brands_and_cars

    Contact = apps.get_model("app", "Contact")
    Brand = apps.get_model("app", "Brand")
    CarModel = apps.get_model("app", "CarModel")

    create_contacts(count=100)
    create_brands_and_cars()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
