# Generated by Django 5.0.1 on 2024-01-31 21:10

from django.db import migrations


def create_initial_contacts(apps, schema_editor):
    # Import the create_contacts function
    from src.app.utils import create_contacts

    # Fetch the Contact model using apps.get_model
    Contact = apps.get_model("app", "Contact")

    # Call the create_contacts function
    create_contacts()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = []
