from app.models import Contact, Brand, CarModel

contacts_list = [
    {
        "id": 1,
        "first_name": "Kathy",
        "last_name": "Lang",
        "email": "kathy.lang@gmail.com",
        "status": "inactive",
    },
    {
        "id": 2,
        "first_name": "Roberto",
        "last_name": "Perez",
        "email": "roberto.perez@hotmail.com",
        "status": "inactive",
    },
    {
        "id": 3,
        "first_name": "Cody",
        "last_name": "House",
        "email": "cody.house@yahoo.com",
        "status": "inactive",
    },
    {
        "id": 4,
        "first_name": "Brittany",
        "last_name": "Thomas",
        "email": "brittany.thomas@yahoo.com",
        "status": "inactive",
    },
    {
        "id": 5,
        "first_name": "Tina",
        "last_name": "Hines",
        "email": "tina.hines@yahoo.com",
        "status": "inactive",
    },
    {
        "id": 6,
        "first_name": "Nicholas",
        "last_name": "Smith",
        "email": "nicholas.smith@yahoo.com",
        "status": "inactive",
    },
    {
        "id": 7,
        "first_name": "Robert",
        "last_name": "Bennett",
        "email": "robert.bennett@hotmail.com",
        "status": "inactive",
    },
    {
        "id": 8,
        "first_name": "Sherri",
        "last_name": "Stone",
        "email": "sherri.stone@gmail.com",
        "status": "inactive",
    },
    {
        "id": 9,
        "first_name": "Nichole",
        "last_name": "Hart",
        "email": "nichole.hart@gmail.com",
        "status": "active",
    },
    {
        "id": 10,
        "first_name": "Kelly",
        "last_name": "Hines",
        "email": "kelly.hines@hotmail.com",
        "status": "active",
    },
    {
        "id": 11,
        "first_name": "Annette",
        "last_name": "Munoz",
        "email": "annette.munoz@yahoo.com",
        "status": "active",
    },
    {
        "id": 12,
        "first_name": "Matthew",
        "last_name": "Conner",
        "email": "matthew.conner@gmail.com",
        "status": "active",
    },
    {
        "id": 13,
        "first_name": "Miranda",
        "last_name": "Beck",
        "email": "miranda.beck@yahoo.com",
        "status": "active",
    },
    {
        "id": 14,
        "first_name": "Michelle",
        "last_name": "Wilson",
        "email": "michelle.wilson@yahoo.com",
        "status": "active",
    },
    {
        "id": 15,
        "first_name": "Sarah",
        "last_name": "Collins",
        "email": "sarah.collins@hotmail.com",
        "status": "active",
    },
    {
        "id": 16,
        "first_name": "Jack",
        "last_name": "Hall",
        "email": "jack.hall@gmail.com",
        "status": "active",
    },
    {
        "id": 17,
        "first_name": "Brandon",
        "last_name": "Taylor",
        "email": "brandon.taylor@gmail.com",
        "status": "active",
    },
    {
        "id": 18,
        "first_name": "Stacey",
        "last_name": "Stevens",
        "email": "stacey.stevens@gmail.com",
        "status": "active",
    },
    {
        "id": 19,
        "first_name": "Brandon",
        "last_name": "Pitts",
        "email": "brandon.pitts@gmail.com",
        "status": "inactive",
    },
    {
        "id": 20,
        "first_name": "Matthew",
        "last_name": "Bowers",
        "email": "matthew.bowers@hotmail.com",
        "status": "inactive",
    },
    {
        "id": 21,
        "first_name": "John",
        "last_name": "Mccullough",
        "email": "john.mccullough@yahoo.com",
        "status": "inactive",
    },
    {
        "id": 22,
        "first_name": "Lisa",
        "last_name": "Bartlett",
        "email": "lisa.bartlett@gmail.com",
        "status": "active",
    },
    {
        "id": 23,
        "first_name": "Brittany",
        "last_name": "Buck",
        "email": "brittany.buck@yahoo.com",
        "status": "active",
    },
    {
        "id": 24,
        "first_name": "Elizabeth",
        "last_name": "Campbell",
        "email": "elizabeth.campbell@gmail.com",
        "status": "inactive",
    },
    {
        "id": 25,
        "first_name": "Emily",
        "last_name": "Maldonado",
        "email": "emily.maldonado@hotmail.com",
        "status": "active",
    },
    {
        "id": 26,
        "first_name": "Andrew",
        "last_name": "Murphy",
        "email": "andrew.murphy@gmail.com",
        "status": "inactive",
    },
    {
        "id": 27,
        "first_name": "Kristen",
        "last_name": "Ramsey",
        "email": "kristen.ramsey@hotmail.com",
        "status": "active",
    },
    {
        "id": 28,
        "first_name": "Jason",
        "last_name": "Williams",
        "email": "jason.williams@hotmail.com",
        "status": "active",
    },
    {
        "id": 29,
        "first_name": "Deborah",
        "last_name": "Wagner",
        "email": "deborah.wagner@yahoo.com",
        "status": "active",
    },
    {
        "id": 30,
        "first_name": "Paula",
        "last_name": "Fisher",
        "email": "paula.fisher@yahoo.com",
        "status": "active",
    },
    {
        "id": 31,
        "first_name": "Alicia",
        "last_name": "Clark",
        "email": "alicia.clark@yahoo.com",
        "status": "inactive",
    },
    {
        "id": 32,
        "first_name": "James",
        "last_name": "Holt",
        "email": "james.holt@hotmail.com",
        "status": "active",
    },
    {
        "id": 33,
        "first_name": "Laura",
        "last_name": "Davis",
        "email": "laura.davis@gmail.com",
        "status": "active",
    },
    {
        "id": 34,
        "first_name": "Jason",
        "last_name": "Richardson",
        "email": "jason.richardson@yahoo.com",
        "status": "inactive",
    },
    {
        "id": 35,
        "first_name": "Richard",
        "last_name": "Jordan",
        "email": "richard.jordan@gmail.com",
        "status": "active",
    },
    {
        "id": 36,
        "first_name": "Natalie",
        "last_name": "Armstrong",
        "email": "natalie.armstrong@hotmail.com",
        "status": "active",
    },
    {
        "id": 37,
        "first_name": "Matthew",
        "last_name": "Hunt",
        "email": "matthew.hunt@yahoo.com",
        "status": "inactive",
    },
    {
        "id": 38,
        "first_name": "Joseph",
        "last_name": "Maldonado",
        "email": "joseph.maldonado@gmail.com",
        "status": "inactive",
    },
    {
        "id": 39,
        "first_name": "Caleb",
        "last_name": "White",
        "email": "caleb.white@hotmail.com",
        "status": "active",
    },
    {
        "id": 40,
        "first_name": "Andrew",
        "last_name": "Dodson",
        "email": "andrew.dodson@hotmail.com",
        "status": "inactive",
    },
    {
        "id": 41,
        "first_name": "Veronica",
        "last_name": "Cortez",
        "email": "veronica.cortez@hotmail.com",
        "status": "active",
    },
    {
        "id": 42,
        "first_name": "Jesse",
        "last_name": "Arroyo",
        "email": "jesse.arroyo@gmail.com",
        "status": "active",
    },
    {
        "id": 43,
        "first_name": "Tina",
        "last_name": "Jensen",
        "email": "tina.jensen@yahoo.com",
        "status": "active",
    },
    {
        "id": 44,
        "first_name": "Todd",
        "last_name": "Gallagher",
        "email": "todd.gallagher@gmail.com",
        "status": "active",
    },
    {
        "id": 45,
        "first_name": "Roberto",
        "last_name": "Anderson",
        "email": "roberto.anderson@hotmail.com",
        "status": "active",
    },
    {
        "id": 46,
        "first_name": "Stacey",
        "last_name": "Morrison",
        "email": "stacey.morrison@yahoo.com",
        "status": "inactive",
    },
    {
        "id": 47,
        "first_name": "David",
        "last_name": "Hicks",
        "email": "david.hicks@yahoo.com",
        "status": "active",
    },
    {
        "id": 48,
        "first_name": "Richard",
        "last_name": "Tucker",
        "email": "richard.tucker@gmail.com",
        "status": "active",
    },
    {
        "id": 49,
        "first_name": "Miguel",
        "last_name": "Baker",
        "email": "miguel.baker@yahoo.com",
        "status": "inactive",
    },
    {
        "id": 50,
        "first_name": "Antonio",
        "last_name": "Flynn",
        "email": "antonio.flynn@gmail.com",
        "status": "active",
    },
    {
        "id": 51,
        "first_name": "Katrina",
        "last_name": "Butler",
        "email": "katrina.butler@gmail.com",
        "status": "inactive",
    },
    {
        "id": 52,
        "first_name": "Jennifer",
        "last_name": "Pitts",
        "email": "jennifer.pitts@hotmail.com",
        "status": "active",
    },
    {
        "id": 53,
        "first_name": "Randall",
        "last_name": "Sanchez",
        "email": "randall.sanchez@gmail.com",
        "status": "active",
    },
    {
        "id": 54,
        "first_name": "Sara",
        "last_name": "Garcia",
        "email": "sara.garcia@gmail.com",
        "status": "inactive",
    },
    {
        "id": 55,
        "first_name": "Scott",
        "last_name": "Edwards",
        "email": "scott.edwards@gmail.com",
        "status": "active",
    },
    {
        "id": 56,
        "first_name": "Kelly",
        "last_name": "Arnold",
        "email": "kelly.arnold@gmail.com",
        "status": "inactive",
    },
    {
        "id": 57,
        "first_name": "Jeffrey",
        "last_name": "Johnson",
        "email": "jeffrey.johnson@hotmail.com",
        "status": "active",
    },
    {
        "id": 58,
        "first_name": "Carlos",
        "last_name": "Jennings",
        "email": "carlos.jennings@hotmail.com",
        "status": "inactive",
    },
    {
        "id": 59,
        "first_name": "Jodi",
        "last_name": "Gray",
        "email": "jodi.gray@hotmail.com",
        "status": "active",
    },
    {
        "id": 60,
        "first_name": "James",
        "last_name": "Davis",
        "email": "james.davis@yahoo.com",
        "status": "inactive",
    },
    {
        "id": 61,
        "first_name": "Anita",
        "last_name": "Day",
        "email": "anita.day@gmail.com",
        "status": "active",
    },
    {
        "id": 62,
        "first_name": "Christopher",
        "last_name": "Gilbert",
        "email": "christopher.gilbert@gmail.com",
        "status": "inactive",
    },
    {
        "id": 63,
        "first_name": "David",
        "last_name": "Farrell",
        "email": "david.farrell@yahoo.com",
        "status": "active",
    },
    {
        "id": 64,
        "first_name": "Elizabeth",
        "last_name": "Williams",
        "email": "elizabeth.williams@gmail.com",
        "status": "inactive",
    },
    {
        "id": 65,
        "first_name": "Bill",
        "last_name": "Walters",
        "email": "bill.walters@hotmail.com",
        "status": "active",
    },
    {
        "id": 66,
        "first_name": "Carla",
        "last_name": "Jones",
        "email": "carla.jones@gmail.com",
        "status": "inactive",
    },
    {
        "id": 67,
        "first_name": "Tiffany",
        "last_name": "Berry",
        "email": "tiffany.berry@yahoo.com",
        "status": "inactive",
    },
    {
        "id": 68,
        "first_name": "Eddie",
        "last_name": "Mclean",
        "email": "eddie.mclean@yahoo.com",
        "status": "active",
    },
    {
        "id": 69,
        "first_name": "Amanda",
        "last_name": "Johns",
        "email": "amanda.johns@gmail.com",
        "status": "inactive",
    },
    {
        "id": 70,
        "first_name": "Jennifer",
        "last_name": "Gray",
        "email": "jennifer.gray@gmail.com",
        "status": "active",
    },
    {
        "id": 71,
        "first_name": "Melinda",
        "last_name": "Whitney",
        "email": "melinda.whitney@hotmail.com",
        "status": "inactive",
    },
    {
        "id": 72,
        "first_name": "Vanessa",
        "last_name": "Carr",
        "email": "vanessa.carr@gmail.com",
        "status": "inactive",
    },
    {
        "id": 73,
        "first_name": "Alyssa",
        "last_name": "Riley",
        "email": "alyssa.riley@gmail.com",
        "status": "inactive",
    },
    {
        "id": 74,
        "first_name": "Sarah",
        "last_name": "Torres",
        "email": "sarah.torres@yahoo.com",
        "status": "active",
    },
    {
        "id": 75,
        "first_name": "Tanya",
        "last_name": "Alexander",
        "email": "tanya.alexander@gmail.com",
        "status": "active",
    },
    {
        "id": 76,
        "first_name": "Kaitlyn",
        "last_name": "Baker",
        "email": "kaitlyn.baker@gmail.com",
        "status": "active",
    },
    {
        "id": 77,
        "first_name": "Lori",
        "last_name": "Kim",
        "email": "lori.kim@hotmail.com",
        "status": "active",
    },
    {
        "id": 78,
        "first_name": "Jeff",
        "last_name": "Pace",
        "email": "jeff.pace@gmail.com",
        "status": "active",
    },
    {
        "id": 79,
        "first_name": "Christopher",
        "last_name": "Mclaughlin",
        "email": "christopher.mclaughlin@yahoo.com",
        "status": "active",
    },
    {
        "id": 80,
        "first_name": "Erica",
        "last_name": "Suarez",
        "email": "erica.suarez@hotmail.com",
        "status": "inactive",
    },
    {
        "id": 81,
        "first_name": "Steven",
        "last_name": "Hicks",
        "email": "steven.hicks@gmail.com",
        "status": "active",
    },
    {
        "id": 82,
        "first_name": "Emily",
        "last_name": "Graham",
        "email": "emily.graham@gmail.com",
        "status": "active",
    },
    {
        "id": 83,
        "first_name": "Austin",
        "last_name": "Villarreal",
        "email": "austin.villarreal@gmail.com",
        "status": "inactive",
    },
    {
        "id": 84,
        "first_name": "Rebecca",
        "last_name": "Smith",
        "email": "rebecca.smith@hotmail.com",
        "status": "inactive",
    },
    {
        "id": 85,
        "first_name": "Daniel",
        "last_name": "Booth",
        "email": "daniel.booth@gmail.com",
        "status": "inactive",
    },
    {
        "id": 86,
        "first_name": "Alexandra",
        "last_name": "Underwood",
        "email": "alexandra.underwood@yahoo.com",
        "status": "active",
    },
    {
        "id": 87,
        "first_name": "Ashley",
        "last_name": "Mills",
        "email": "ashley.mills@yahoo.com",
        "status": "active",
    },
    {
        "id": 88,
        "first_name": "Ashley",
        "last_name": "Vaughn",
        "email": "ashley.vaughn@yahoo.com",
        "status": "active",
    },
    {
        "id": 89,
        "first_name": "Kimberly",
        "last_name": "Gomez",
        "email": "kimberly.gomez@hotmail.com",
        "status": "active",
    },
    {
        "id": 90,
        "first_name": "Kristin",
        "last_name": "Davis",
        "email": "kristin.davis@yahoo.com",
        "status": "inactive",
    },
    {
        "id": 91,
        "first_name": "Gerald",
        "last_name": "James",
        "email": "gerald.james@gmail.com",
        "status": "inactive",
    },
    {
        "id": 92,
        "first_name": "Alyssa",
        "last_name": "Adams",
        "email": "alyssa.adams@hotmail.com",
        "status": "inactive",
    },
    {
        "id": 93,
        "first_name": "Hector",
        "last_name": "Smith",
        "email": "hector.smith@yahoo.com",
        "status": "active",
    },
    {
        "id": 94,
        "first_name": "Amanda",
        "last_name": "Hill",
        "email": "amanda.hill@hotmail.com",
        "status": "inactive",
    },
    {
        "id": 95,
        "first_name": "Karla",
        "last_name": "Thornton",
        "email": "karla.thornton@yahoo.com",
        "status": "inactive",
    },
    {
        "id": 96,
        "first_name": "Elizabeth",
        "last_name": "Johnson",
        "email": "elizabeth.johnson@hotmail.com",
        "status": "active",
    },
    {
        "id": 97,
        "first_name": "Benjamin",
        "last_name": "Chambers",
        "email": "benjamin.chambers@yahoo.com",
        "status": "active",
    },
    {
        "id": 98,
        "first_name": "James",
        "last_name": "Coleman",
        "email": "james.coleman@yahoo.com",
        "status": "active",
    },
    {
        "id": 99,
        "first_name": "Joseph",
        "last_name": "Johnson",
        "email": "joseph.johnson@hotmail.com",
        "status": "active",
    },
    {
        "id": 100,
        "first_name": "Amanda",
        "last_name": "Roman",
        "email": "amanda.roman@gmail.com",
        "status": "inactive",
    },
]

brands_list = [
    "Toyota",
    "Ford",
    "Honda",
    "Chevrolet",
]

car_models_list = {
    "Toyota": [
        "4Runner",
        "Avalon",
        "Camry",
        "Corolla",
        "Highlander",
        "Land Cruiser",
        "Prius",
        "RAV4",
        "Sequoia",
        "Sienna",
        "Tacoma",
        "Tundra",
        "Yaris",
    ],
    "Ford": [
        "Bronco",
        "EcoSport",
        "Edge",
        "Escape",
        "Expedition",
        "Explorer",
        "F-150",
        "F-250",
        "F-350",
        "F-450",
        "Fiesta",
        "Flex",
        "Focus",
        "Fusion",
        "Mustang",
        "Ranger",
        "Taurus",
        "Transit",
    ],
    "Honda": [
        "Accord",
        "Civic",
        "Clarity",
        "CR-V",
        "Fit",
        "HR-V",
        "Insight",
        "Odyssey",
        "Passport",
        "Pilot",
        "Ridgeline",
    ],
    "Chevrolet": [
        "Blazer",
        "Bolt EV",
        "Camaro",
        "Colorado",
        "Corvette",
        "Equinox",
        "Express",
        "Impala",
        "Malibu",
        "Silverado",
        "Sonic",
        "Spark",
        "Suburban",
        "Tahoe",
        "Trailblazer",
        "Traverse",
        "Trax",
    ],
}


def source_link(link):
    return "https://github.com/iwanalabs/django-htmx-components/blob/main/src/" + link


def delete_contacts():
    Contact.objects.all().delete()


def create_contacts(contacts=contacts_list, count=None):
    for contact in contacts[:count]:
        Contact.objects.get_or_create(
            id=contact["id"],
            defaults={
                "first_name": contact["first_name"],
                "last_name": contact["last_name"],
                "email": contact["email"],
                "status": contact["status"],
            },
        )


def create_brands_and_cars():
    for brand in brands_list:
        Brand.objects.get_or_create(name=brand)
        for car_model in car_models_list[brand]:
            CarModel.objects.get_or_create(
                name=car_model, brand=Brand.objects.get(name=brand)
            )
